/**
 *
 * $Id$
 */
package org.sociotech.communitymashup.application.validation;

import org.sociotech.communitymashup.application.Configuration;

/**
 * A sample validator interface for {@link org.sociotech.communitymashup.application.ConfigurableElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConfigurableElementValidator {
	boolean validate();

	boolean validateConfiguration(Configuration value);
	boolean validateName(String value);
	boolean validateConfigurationImage(String value);
	boolean validateDescription(String value);
	boolean validateChangeable(Boolean value);
	boolean validateHidden(Boolean value);
	boolean validateIdent(String value);
}
