/**
 *
 * $Id$
 */
package org.sociotech.communitymashup.application.validation;

import org.sociotech.communitymashup.application.Mashup;
import org.sociotech.communitymashup.application.Security;

/**
 * A sample validator interface for {@link org.sociotech.communitymashup.application.Interface}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InterfaceValidator {
	boolean validate();

	boolean validateSecurity(Security value);
	boolean validateUrlSuffix(String value);
	boolean validateMashup(Mashup value);
	boolean validateFrontEndCaching(Boolean value);
}
