/**
 *
 * $Id$
 */
package org.sociotech.communitymashup.application.validation;

import org.eclipse.emf.common.util.EList;

import org.sociotech.communitymashup.application.Interface;
import org.sociotech.communitymashup.application.Mashup;
import org.sociotech.communitymashup.application.MashupAdmin;

/**
 * A sample validator interface for {@link org.sociotech.communitymashup.application.MashupContainer}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MashupContainerValidator {
	boolean validate();

	boolean validateMashups(EList<Mashup> value);
	boolean validateAllMashupAdmins(EList<MashupAdmin> value);
	boolean validateBackupConfiguration(Boolean value);
	boolean validateBackupIntervall(Integer value);
	boolean validateDefaultMashups(EList<Mashup> value);
	boolean validateSourceConfigurations(EList<Mashup> value);
	boolean validateInterfaceConfigurations(EList<Interface> value);
	boolean validateImmediateSave(Boolean value);
	boolean validateCreateAccountsAtLoginTry(Boolean value);
	boolean validateIdentCounter(Integer value);
}
