/**
 *
 * $Id$
 */
package org.sociotech.communitymashup.application.validation;

import org.eclipse.emf.common.util.EList;

import org.sociotech.communitymashup.application.Mashup;

/**
 * A sample validator interface for {@link org.sociotech.communitymashup.application.MashupAdmin}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MashupAdminValidator {
	boolean validate();

	boolean validateProvider(String value);
	boolean validateId(String value);
	boolean validateConfigurableMashups(EList<Mashup> value);
	boolean validateName(String value);
	boolean validateLocalIdent(String value);
	boolean validateIsConfigurationAdmin(Boolean value);
	boolean validateProfileImage(String value);
	boolean validateEmail(String value);
}
