/**
 *
 * $Id$
 */
package org.sociotech.communitymashup.application.validation;

import org.eclipse.emf.common.util.EList;

import org.sociotech.communitymashup.application.OAuthAdmin;
import org.sociotech.communitymashup.application.OAuthClientConfig;

/**
 * A sample validator interface for {@link org.sociotech.communitymashup.application.OAuthConfig}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OAuthConfigValidator {
	boolean validate();

	boolean validateClients(EList<OAuthClientConfig> value);
	boolean validateAdmins(EList<OAuthAdmin> value);
	boolean validateUseScopeInterfaceOnRedirect(Boolean value);
}
