/**
 *
 * $Id$
 */
package org.sociotech.communitymashup.application.validation;


/**
 * A sample validator interface for {@link org.sociotech.communitymashup.application.OAuthClientScope}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OAuthClientScopeValidator {
	boolean validate();

	boolean validatePositiveTag(String value);
	boolean validateNegativeTag(String value);
	boolean validatePositiveMetaTag(String value);
	boolean validateNegativeMetaTag(String value);
	boolean validatePositiveCategory(String value);
	boolean validateNegativeCategory(String value);
	boolean validatePositivePerson(String value);
	boolean validateNegativePerson(String value);
	boolean validatePositiveOrganisation(String value);
	boolean validateNegativeOrganisation(String value);
	boolean validateIdentSpecification(Boolean value);
	boolean validateAllowPersons(Boolean value);
	boolean validateAllowContents(Boolean value);
	boolean validateAllowOrganisations(Boolean value);
	boolean validateMaximumAge(String value);
}
