/**
 *
 * $Id$
 */
package org.sociotech.communitymashup.data.validation;


/**
 * A sample validator interface for {@link org.sociotech.communitymashup.data.Attachment}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AttachmentValidator {
	boolean validate();

	boolean validateFileUrl(String value);
	boolean validateCachedFileUrl(String value);
	boolean validateCachedOnly(Boolean value);
	boolean validateFileExtension(String value);
	boolean validateFileIdentifier(String value);
	boolean validateCachedFileName(String value);
	boolean validateNoCache(Boolean value);
}
