/**
 *
 * $Id$
 */
package org.sociotech.communitymashup.data.validation;

import org.eclipse.emf.common.util.EList;

import org.sociotech.communitymashup.data.Content;
import org.sociotech.communitymashup.data.Document;
import org.sociotech.communitymashup.data.Person;
import org.sociotech.communitymashup.data.Transformation;
import org.sociotech.communitymashup.data.Video;

/**
 * A sample validator interface for {@link org.sociotech.communitymashup.data.Content}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ContentValidator {
	boolean validate();

	boolean validateContents(EList<Content> value);
	boolean validateContributors(EList<Person> value);
	boolean validateAuthor(Person value);
	boolean validateDocuments(EList<Document> value);
	boolean validateParentContent(Content value);
	boolean validateLocale(String value);
	boolean validateTransformations(EList<Transformation> value);
	boolean validateVideos(EList<Video> value);
}
