/**
 *
 * $Id$
 */
package org.sociotech.communitymashup.data.validation;

import java.util.Date;

import org.eclipse.emf.common.util.EList;

import org.sociotech.communitymashup.application.Mashup;

import org.sociotech.communitymashup.data.DeletedItem;
import org.sociotech.communitymashup.data.Item;

/**
 * A sample validator interface for {@link org.sociotech.communitymashup.data.DataSet}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DataSetValidator {
	boolean validate();

	boolean validateItems(EList<Item> value);
	boolean validateCacheFolder(String value);
	boolean validateCacheFileAttachements(Boolean value);
	boolean validateSetUp(Mashup value);
	boolean validateLastModified(Date value);
	boolean validateLogLevel(Integer value);
	boolean validateIdentCounter(Long value);
	boolean validateIdentPrefix(String value);
	boolean validateCreated(Date value);
	boolean validateKeepDeletedItemsList(Boolean value);
	boolean validateItemsDeleted(EList<DeletedItem> value);
}
