/**
 *
 * $Id$
 */
package org.sociotech.communitymashup.data.validation;

import org.eclipse.emf.common.util.EList;

import org.sociotech.communitymashup.data.Binary;
import org.sociotech.communitymashup.data.Category;
import org.sociotech.communitymashup.data.Connection;
import org.sociotech.communitymashup.data.Image;
import org.sociotech.communitymashup.data.MetaInformation;
import org.sociotech.communitymashup.data.StarRanking;
import org.sociotech.communitymashup.data.Tag;
import org.sociotech.communitymashup.data.ThumbRanking;
import org.sociotech.communitymashup.data.ViewRanking;

/**
 * A sample validator interface for {@link org.sociotech.communitymashup.data.InformationObject}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InformationObjectValidator {
	boolean validate();

	boolean validateCategories(EList<Category> value);
	boolean validateTags(EList<Tag> value);
	boolean validateImages(EList<Image> value);
	boolean validateStarRankings(EList<StarRanking> value);
	boolean validateThumbRankings(EList<ThumbRanking> value);
	boolean validateViewRankings(EList<ViewRanking> value);
	boolean validateName(String value);
	boolean validateConnectedTo(EList<Connection> value);
	boolean validateConnectedBy(EList<Connection> value);
	boolean validateBinaries(EList<Binary> value);
	boolean validateMainCategory(Category value);
	boolean validateMetaInformations(EList<MetaInformation> value);
	boolean validateAlternativeNames(String value);
	boolean validateVerifiedName(Boolean value);
}
