/**
 *
 * $Id$
 */
package org.sociotech.communitymashup.data.validation;

import java.util.Date;

import org.eclipse.emf.common.util.EList;

import org.sociotech.communitymashup.data.DataSet;
import org.sociotech.communitymashup.data.Identifier;
import org.sociotech.communitymashup.data.Item;
import org.sociotech.communitymashup.data.MetaTag;

/**
 * A sample validator interface for {@link org.sociotech.communitymashup.data.Item}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ItemValidator {
	boolean validate();

	boolean validateDataSet(DataSet value);
	boolean validateIdent(String value);
	boolean validateUri(String value);
	boolean validateStringValue(String value);
	boolean validateLastModified(Date value);
	boolean validateCreated(Date value);
	boolean validateMetaTags(EList<MetaTag> value);
	boolean validateIdentifiedBy(EList<Identifier> value);
	boolean validateDeleteOnDelete(EList<Item> value);
	boolean validateDeletedIfDeleted(EList<Item> value);
	boolean validateForcedDeleteOnDelete(EList<Item> value);
	boolean validateForcedDeletedIfDeleted(EList<Item> value);
}
