/**
 *
 * $Id$
 */
package org.sociotech.communitymashup.data.validation;

import org.eclipse.emf.common.util.EList;

import org.sociotech.communitymashup.data.IndoorLocation;

/**
 * A sample validator interface for {@link org.sociotech.communitymashup.data.Location}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LocationValidator {
	boolean validate();

	boolean validateStreet(String value);
	boolean validateHouseNumber(String value);
	boolean validateZipCode(String value);
	boolean validateCountry(String value);
	boolean validateLongitude(String value);
	boolean validateLatitude(String value);
	boolean validateCity(String value);
	boolean validateIndoorLocations(EList<IndoorLocation> value);
	boolean validateState(String value);
}
