/**
 *
 * $Id$
 */
package org.sociotech.communitymashup.data.validation;

import java.util.Date;

import org.eclipse.emf.common.util.EList;

import org.sociotech.communitymashup.data.Content;
import org.sociotech.communitymashup.data.Organisation;
import org.sociotech.communitymashup.data.Person;
import org.sociotech.communitymashup.data.Ranking;

/**
 * A sample validator interface for {@link org.sociotech.communitymashup.data.Person}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PersonValidator {
	boolean validate();

	boolean validateLastname(String value);
	boolean validateFirstname(String value);
	boolean validateLeaderOf(EList<Organisation> value);
	boolean validateParticipates(EList<Organisation> value);
	boolean validateAuthored(EList<Content> value);
	boolean validateContributed(EList<Content> value);
	boolean validateDateOfBirth(Date value);
	boolean validatePersons(EList<Person> value);
	boolean validateTitle(String value);
	boolean validateRanked(EList<Ranking> value);
}
