/**
 *
 * $Id$
 */
package org.sociotech.communitymashup.data.validation;

import org.sociotech.communitymashup.data.InformationObject;

/**
 * A sample validator interface for {@link org.sociotech.communitymashup.data.StarRanking}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StarRankingValidator {
	boolean validate();

	boolean validateRankedInformationObject(InformationObject value);
	boolean validateNormalizedValue(Double value);
}
