/**
 *
 * $Id$
 */
package org.sociotech.communitymashup.data.validation;

import org.eclipse.emf.common.util.EList;

import org.sociotech.communitymashup.data.InformationObject;

/**
 * A sample validator interface for {@link org.sociotech.communitymashup.data.Tag}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TagValidator {
	boolean validate();

	boolean validateTagged(EList<InformationObject> value);
}
