/**
 *
 * $Id$
 */
package org.sociotech.communitymashup.collection.validation;

import org.eclipse.emf.common.util.EList;

import org.sociotech.communitymashup.data.DataSet;
import org.sociotech.communitymashup.data.Item;

/**
 * A sample validator interface for {@link org.sociotech.communitymashup.collection.ItemsCollection}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ItemsCollectionValidator {
	boolean validate();

	boolean validateItems(EList<Item> value);
	boolean validateDataSet(DataSet value);
}
